@startuml
'https://plantuml.com/sequence-diagram

autonumber


Core -> ProcessingService: ProcessAll
ProcessingService -> Instance as "Collision (Implementing ProcessingServiceInterface)": Process
Instance -> Instance: Check for collisions

alt "Collision found"
    Instance -> Instance: Remove lives from entities

else "No collision found"
    Instance -> Instance: Continue

end



@enduml